
services:
  rabbitmq:
    image: rabbitmq:4.0.3-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=secretRabbitMQ
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./development/rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5673:5672